# create one iris with both apache2 and nginx webgateway

services:
    iris-a:      
        image: containers.intersystems.com/intersystems/irishealth-arm64:2024.1
        container_name: iris-a
        hostname: irisa
        ports:
            - 1972:1972
            - 9001-9005:9001-9005 # test ports
        volumes:
            - ./iris2024:/external
        command: 
            --key /external/i4h_Enterprise_contianer_Ubuntu_ARM64.ISCkey
        #    --after /external/code_install.sh
        #    --instance irisa
        environment: 
            - TZ=CST-8
            - ISC_CPF_MERGE_FILE=/external/merge.cpf
        #    - ISC_DATA_DIRECTORY=/dur/iconfig
       
    webgateway-nginx:
        image: containers.intersystems.com/intersystems/webgateway-nginx-arm64:2024.1
        container_name: wg-n
        hostname: wg-n
        ports:
            - "8081:80"
            - "444:443"
        volumes:
            - ./webgateway:/external
        environment:
            - TZ=CST-8
            - ISC_CSP_CONF_FILE=/external/CSP-nginx.conf
            - ISC_CSP_INI_FILE=/external/CSP.ini
            - ISC_DATA_DIRECTORY=/external/durable
   
    
    # webgateway-apache:
    #     image: containers.intersystems.com/intersystems/webgateway-arm64:2024.1
    #     container_name: wg-a
    #     hostname: wg-a
    #     ports:
    #         - "8080:80"
    #         - "443:443"
    #     volumes:
    #         - ./webgateway:/external
    #     environment:
    #         - TZ=CST-8
    #         - ISC_CSP_CONF_FILE=/external/CSP-apache.conf
    #         - ISC_CSP_INI_FILE=/external/CSP.ini
    #         - ISC_DATA_DIRECTORY=/external/durable
    #         # 下面这些env肯定不行 
    #         # - IRIS_HOST=iris-a
    #         # - IRIS_PORT=1972
    #         # - "SYSTEM_MANAGER=*.*.*.*"        
